apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  labels:
    app: nextjs-app
spec:
  selector:
    app: nextjs-app
  type: NodePort
  ports:
    - port: 3000       
      targetPort: 3000 
      nodePort: 30080  
