apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  labels:
    app: nextjs-app
spec:
  selector:
    app: nextjs-app
  type: NodePort
  ports:
    - port: 3000       # service port
      targetPort: 3000 # container port
      nodePort: 30080  # optional fixed NodePort (30000–32767); or remove line to auto-assign
